version: '3.8'
services:
  int-products-ms:
    build:
      context: ./int-products-ms
    image: int-products-ms:latest
    container_name: int-products-ms
    ports:
      - "3001:3000"
    volumes:
      - ./int-products-ms:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge