version: '3.8'
services:
  int-products-ms:
    build:
      context: ./int-products-ms
    image: int-products-ms:latest
    container_name: int-products-ms
    ports:
      - "3000:3000"
    volumes:
      - ./int-products-ms:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

  int-category-ms:
    build:
      context: ./int-category-ms
    image: int-category-ms:latest
    container_name: int-category-ms
    ports:
      - "3001:3001"
    volumes:
      - ./int-category-ms:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

  fcd-search-products:
    build:
      context: ./fcd-search-products
    image: fcd-search-products:latest
    container_name: fcd-search-products
    ports:
      - "3002:3002"
    volumes:
      - ./fcd-search-products:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge